### ISSUE TITLE
Changes in Lingo 2.x will most likely break SG

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticGlossary#10]
Lingo 2.x [0] changes which will most likely break SG functionality in terms of:

- Autoloading is not secured to happen in time (SG uses PSR-4 by the time Composer calls the vendor map)
- Missing [0] breaks the tests and fails in general
- `extension.json` has no mechanism to secure that Lingo is loaded before SG let alone the manual requirement for manual invocation

@s7eph4n @kghbln FYI, I'm guessing this going to be the same drama as with SFS.

[0] https://github.com/wikimedia/mediawiki-extensions-Lingo/commit/7dfb0381be14b7846379a0df2cfb41b07052175a

[1] https://github.com/SemanticMediaWiki/SemanticGlossary/blob/master/SemanticGlossary.php#L30-L32

**Comment by s7eph4n** [comment]
My intention is to keep Lingo and SG in line. Let's see if I can work it out.

**Comment by s7eph4n** [comment]
Seems to work so far. :)
