### ISSUE TITLE
Property NS is not browsable 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticGlossary#13]
@s7eph4n FYI This is the issue I run into [0] when the extension was loaded using `wfLoadExtension` (https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1424) and mitigated using https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1440 (this is not going to be backported).

[0] https://github.com/SemanticMediaWiki/SemanticGlossary/pull/12#issuecomment-193655613

![image](https://cloud.githubusercontent.com/assets/1245473/13725374/f175a18c-e89f-11e5-9e2a-3febe0d492db.png)

refs https://www.mediawiki.org/wiki/Topic:T01jqo97o1n384lh

**Comment by s7eph4n** [comment]
I am not sure that this is related, nl.scoutwiki.org is running MW 1.26.2.
If I understood the issue correctly (and I am not sure I did), this only affects MW 1.27 with SMW <2.4, right?

**Comment by mwjames** [comment]
> If I understood the issue correctly (and I am not sure I did), this only affects MW 1.27 with SMW <2.4, right?

I found that when running on 1.26.0.

**Comment by mwjames** [comment]
1.27 just elevated to issue to a whole new level.

**Comment by mwjames** [comment]
See https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1424#issuecomment-207100081.

**Comment by mwjames** [comment]
While testing with an enabled `wfLoadExtension('SemanticGlossary')`, I observed the issue and it is expected to be addressed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1886.
