### ISSUE TITLE
"How do I get the plural variant of a term into the definition"?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticGlossary#15]
was asked by Koalopete [0]:

> Hi, how do I get the plural variant of a term into the definition so that "website" and "websites" share the same definition? cheers

```
{{#subobject:
 |Glossary-Term=website,websites|+sep=,
 |Glossary-Definition=foo foo
 |Glossary-Link={{FULLPAGENAME}}
}}
```

PS: @s7eph4n @kghbln I'm not sure [0] is the correct channel.

[0] https://www.mediawiki.org/wiki/Topic:T6jo9kqf5efv0k2v

**Comment by s7eph4n** [comment]
Works for me exactly like that.

Questions as cited on the [extension website](https://www.mediawiki.org/wiki/Extension:Semantic_Glossary#Contact) should go to
*    the Semantic Mediawiki User mailing list (preferred)
*    the Semantic Glossary discussion page
*    the author

If you had not pointed this out, I'd never have noticed this. (So, thanks! :) )
I'll leave a link to here.
