### ISSUE TITLE
Page Special:Preferences is broken after manual installation

### ISSUE THREAD

**Issue by Adambel** [SemanticMediaWiki/SemanticGlossary#25]
Steps to reproduce:

1. Download the ZIP file and extract it. 
2. Upload the SemanticGlossary folder to the extensions folder of your wiki
3. Add `wfLoadExtension('SemanticGlossary');` to `LocalSettings.php` and upload it to the root of your wiki
4. Go to the Special:Preferences page and change a setting (e.g. select the checkbox Editing > Show edit toolbar)
5. Click save.
6. The page returns a message saying that your preferences have been saved. 

-> However, they haven't been saved: the state of the checkbox hasn't changed.

7. In `LocalSettings.php` comment or remove `wfLoadExtension('SemanticGlossary');`  and upload it again.
8. Retry steps 4-6

-> The changes have now been saved.

I resolved the issue by installing SemanticGlossary using Composer, which appears to install Lingo in the extensions folder (if I'm not mistaken).

**Comment by s7eph4n** [comment]
Thanks for the bug report. It's fixed in SG 2.0.3.
