### ISSUE TITLE
Warning: Parameter 3 to SG\HookRegistry::SG\{closure}() expected to be a reference

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticGlossary#27]
**Setup**
- MediaWiki 	1.29.0-rc.0 (4e4d48d) 20:01, 15 June 2017
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MariaDB 	10.0.31-MariaDB-1~jessie
- Semantic MediaWiki	3.0.0-alpha (e07691a) 14:22, 19 June 2017
- Semantic Glossary	2.2.0 (74660d3) 07:44, 5 June 2017
- Lingo	2.0.3 (e0eb806) 11:50, 7 June 2017

**Issue**
After [moving a page](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Renommer_une_page&action=submit) I get the following PHP warning:

```
 Warning: Parameter 3 to SG\HookRegistry::SG\{closure}() expected to be a reference, value given in /.../w/includes/Hooks.php on line 186
```

**Comment by mwjames** [comment]
I'm guessing this relates to https://phabricator.wikimedia.org/T118683. In SMW [0] we just removed the reference signature as it was clear that WMF is not providing any viable solution.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/HookRegistry.php#L298-L315
