### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticGlossary#3]
* [ ] Add CI command to `composer.json` ([example](https://github.com/wmde/Diff/blob/master/composer.json#L45-L58))
* [ ] Have TravisCI create an install and run the CI command

**Comment by mwjames** [comment]
[0] to fix Travis.

[0] https://gerrit.wikimedia.org/r/#/c/170529/1/build/travis/before_script.sh

**Comment by JeroenDeDauw** [comment]
I actually do not have the rights to merge it there. Which means I will also not be able to sync changes back. Ping @s7eph4n

**Comment by s7eph4n** [comment]
Merged it.

**Comment by s7eph4n** [comment]
Don't know, how to add you to the group on gerrit. Guess I"ll have to request it somewhere on mw.org.

**Comment by JeroenDeDauw** [comment]
Yeah... that's actually a good reason to not have it on WMF gerrit. You have a ton of people you don't know that have all the rights on the repo, and you can't even add a trusted contributor yourself.

**Comment by JeroenDeDauw** [comment]
I've just merged the wmf master branch with the gh one, so the wmf one is currently out of date.

**Comment by JeroenDeDauw** [comment]
Oh - because of this fix I just realized that this repo does in fact have TravisCI config. I somehow missed that before. I've enabled TravisCI for this repo now.

**Comment by mwjames** [comment]
Travis (refs #6) is :+1: and working against the correct source.

**Comment by mwjames** [comment]
Just use `composer phpunit` from the extension root.

**Comment by JeroenDeDauw** [comment]
\o/

**Comment by JeroenDeDauw** [comment]
@s7eph4n I got rights on the wmf repo now and have synced

**Comment by s7eph4n** [comment]
\o/
