### ISSUE TITLE
Line break in Glossary-Definition resullts in text display after underlined term

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticGlossary#32]
### Setup and configuration

- MW version: 1.27.3
- PHP version: 5.6
- DB (MySQL etc.): 5
- SMW version: 2.5.5
- SG version: 2.2.0
- Lingo version: 2.0.3

### Issue

Glossary-Definitions  that have a simple line break in them result in a correct annotation, but below the underlined Glossary-Item the text after the first line-break is shown

**Comment by mwjames** [comment]
>but below the underlined Glossary-Item the text after the first line-break is shown

I don't want sound like a broken record (yet it seems I do since I repeatedly ask people about this) but what about an example? Can it be observed somewhere? Do we have an example available on the sandbox and if we don't, can we create one?

**Comment by krabina** [comment]
https://sandbox.semantic-mediawiki.org/wiki/Semantic_Glossary_Linebreak

**Comment by kghbln** [comment]
Thanks for providing the example. I believe to have read that you should only use one line, however I may be wrong. In any case having the possibility to have a line break will be a great enhancement or bug fix. I leave it to @s7eph4n to assess.

**Comment by s7eph4n** [comment]
I suspect that's a Lingo bug, but lets keep the bug report here, I like the GitHub UI better.
