### ISSUE TITLE
Deprecated DIProperty methods were removed

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticGlossary#33]
### Setup and configuration

- MediaWiki | 1.30.0 (d0c8f49)19:49, 5. Jan. 2018
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.33-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (388e383) 07:44, 7. Jan. 2018
- Semantic Glossary | 2.2.0 (a9c20ad) 01:07, 24 May 2017
- Lingo | 2.0.3 (b994b74) 00:47, 24 May 2017

### Issue

Due to the removal of these methods the wiki fails with a fatal.

```
 Fatal error: Call to undefined method SMW\DIProperty::registerProperty() in /../w/extensions/SemanticGlossary/src/PropertyRegistry.php on line 87
```

### Solution
A [migration guide](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/migration-guide-3.0.md#register-predefined-property) is available.

```
\Hooks::register( 'SMW::Property::initProperties', function( $propertyRegistry ) {

	$propertyRegistry->registerProperty( '__FOO', '_txt', 'Foo' );

	return true;
} );
```

### See also
The commit that removed the methods: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2944

**Comment by kghbln** [comment]
@s7eph4n FYI I will reinstall on sandbox as soon as fluff is there. :)

**Comment by kghbln** [comment]
@s7eph4n Back in business on sandbox with

```php
## Semantic Glossary
wfLoadExtension( 'SemanticGlossary' );
$wgexLingoPage = 'Glossaire';
$wgexLingoUseNamespaces[NS_SPECIAL] = false;
```

**Comment by s7eph4n** [comment]
Didn't even remember the bug on this, just wanted to get it running again. :)
