### ISSUE TITLE
Set up repo rights

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticGlossary#5]
Current repo write (and merge) rights are:

* SMW org admins (can not be changed)
* SMW org "contributors with push rights" group (very small ATM, just Markus, James, kgh, s7 and me)

@s7eph4n Are you fine with the second group having write access? And does anyone else need to have write access to this repo? (Also, if you can think of someone that should just be in the second group, let me know.)

Only the SMW org admins have admin access ATM. I can create a dedicated SG admin group if someone else (ie @s7eph4n) needs access as well.

**Comment by s7eph4n** [comment]
Ok with me.

**Comment by kghbln** [comment]
@JeroenDeDauw  It will be nice to sync in the tags too for me to fluff up releases on GitHub

**Comment by JeroenDeDauw** [comment]
You can haz

**Comment by kghbln** [comment]
Great, thank you!

**Comment by kghbln** [comment]
OMG, why did I reopen???? I am pretty grumpy today, though.

**Comment by JeroenDeDauw** [comment]
![grumpy](https://cloud.githubusercontent.com/assets/146040/6040794/22dafa36-ac76-11e4-8225-3b77caa5fa1a.jpg)

**Comment by kghbln** [comment]
Yeah, that was me yesterday. :)
