### ISSUE TITLE
Missing marked terms due to LingoParser failing to check for \StubObject 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticGlossary#50]
### Setup and configuration

- MW version: 1.32+
- PHP version:
- DB (MySQL etc.):
- SMW version:
- SG version: 3.0+
- Lingo version: 3.0.0

### Issue

Appeared with SG [0] but the issue lies with the `LingoParser` due to terms not being parsed and marked.

[0] https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Matmunuc/Cascading_Style_Sheet

### Caused by

The invoked `$GLOBALS['wgParser']` can contain a `StubObject` instance therefore the `$parser instanceof Parser` check isn't sufficient and needs to be extended to:

```
	protected function shouldParse( &$parser ) {
		global $wgexLingoUseNamespaces;

		if ( !( $parser instanceof Parser ) && !$parser instanceof \StubObject ) {
			return false;
		}
```

**Comment by mwjames** [comment]
> [0] https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Matmunuc/Cascading_Style_Sheet

The "CSS" is now marked and shows the term making above example obsolete but the issue remains (encountered on a local MW) and should be fixed in Lingo as outlined above.

**Comment by s7eph4n** [comment]
Fixed in https://github.com/wikimedia/mediawiki-extensions-Lingo/commit/807e0eb6f67b393627838bc95017ba4f24212327

**Comment by mwjames** [comment]
> Fixed in wikimedia/mediawiki-extensions-Lingo@807e0eb

@kghbln @s7eph4n Lingo 3.0.1 hasn't been released therefore the fix isn't available to users like [0].

[0] https://www.semantic-mediawiki.org/wiki/Thread:Extension_talk:Semantic_Glossary/Does_it%3F/reply_(2)
