### ISSUE TITLE
SG 4.0 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticGlossary#54]
## Release date

TBD

## Boundaries

- MW: 1.31 - MW 1.33 (CI tested)
- PHP: 7.0 - 7.3 (CI tested)
- SMW: 3+

**Comment by mwjames** [comment]
@kghbln @s7eph4n FYI

**Comment by kghbln** [comment]
MW 1.31+
PHP 7.1+
SMW 3.1 +
