### ISSUE TITLE
Error in MediaWiki 1.35: Call to undefined method ExtensionRegistry::load() 

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticGlossary#56]
### Setup and configuration

- MW version: 1.35.1
- PHP version: 7.3
- DB (MySQL etc.):
- SMW version: 3.2.2

### Issue

Enabling Semantic Glossary in MediaWiki 1.31.5 produces the following error

```
Fatal error: Uncaught Error: Call to undefined method ExtensionRegistry::load() in extensions/SemanticGlossary/SemanticGlossary.php:27 

Stack trace: 
#0 includes/registration/ExtensionRegistry.php(541): SemanticGlossary::initExtension(Array) 
#1 includes/registration/ExtensionRegistry.php(232): ExtensionRegistry->exportExtractedData(Array) 
#2 includes/Setup.php(161): ExtensionRegistry->loadFromQueue() 
#3 includes/WebStart.php(89): require_once('/home/testw...') 
#4 index.php(44): require('...') 
#5 {main} thrown in extensions/SemanticGlossary/SemanticGlossary.php on line 27
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by kghbln** [comment]
Thanks for reporting. Note that SG does not work with MW 1.35+ even if it is loaded.

**Comment by krabina** [comment]
It seems that the followingg approach is working:
* update Semantic Glossary to master
* update Lingo to master 
* envoke both in LocalSettings.php

It works in my setup now in MW 1.35. The only thing I see that is this notice and warning, but only on Special:Version:
```
Notice
: Undefined index: parserhook in
.../extensions/Lingo/src/Lingo.php
on line
89


Warning
: Invalid argument supplied for foreach() in
.../extensions/Lingo/src/Lingo.php
on line
89
```

**Comment by kghbln** [comment]
@krabina And the bubble show?

**Comment by krabina** [comment]
yes: 
![grafik](https://user-images.githubusercontent.com/4318745/107487081-14948700-6b86-11eb-9eb8-eda9b67b73c9.png)

**Comment by kghbln** [comment]
Ok, thanks. Last time on sandbox I had no bubbles. Will give it another shot.

**Comment by kghbln** [comment]
Nope, not working on sandbox. Moreover with Composer I cannot longer install master so I had to check out master with Git. Additionally I to not get the Notices on Special:Version you mentioned. I am giving up on this.

**Comment by krabina** [comment]
did you invoke both in LocalSettings.php, first Lingo, ,then SG?

**Comment by kghbln** [comment]
> did you invoke both in LocalSettings.php, first Lingo, ,then SG?

Sure yes. I guess some other extension may interfere. However I have no time to figure this out a the moment. Also I am on MW 1.35.0-rc2 which I cannot upgrade at the moment. Perhaps MediaWiki is at play to though this would surprise me at the moment.

**Comment by gesinn-it** [comment]
I think a first step could be a current (working) release of Lingo: https://www.mediawiki.org/wiki/Topic:W365ntpdz01m3zif. Not sure if it is really working, since Travis CI seems to be not triggered. Last Travis build is 3 years old: https://travis-ci.org/github/wikimedia/mediawiki-extensions-Lingo/builds. I forked the repo from Github to manually trigger Travis...

**Comment by gesinn-it** [comment]
Lingo definitely requires some love before a next release. All Travis build jobs failed: https://travis-ci.org/github/gesinn-it/mediawiki-extensions-Lingo/builds/758499039

**Comment by gesinn-it** [comment]
Btw. the above mentioned fork of Lingo was not meant to be permanent. It was just to allow manually triggering Travis...

**Comment by kghbln** [comment]
Very much indeed. Heaps of love needed. Helping hands appreciated!

**Comment by krabina** [comment]
I guess this is fixed. 
Latest version 3.0.0 (5feb7e4) 18:51, 21. Jun. 2021 is working for me in 1.35
