### ISSUE TITLE
Update for 1.35

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticGlossary#58]
The [TitleMoveComplete](https://www.mediawiki.org/wiki/Manual:Hooks/TitleMoveComplete) is deprecated in 1.35.

**Comment by kghbln** [comment]
@hexmode Thanks for the pull #59 which as it looks to me fixes this very issue. Thus closing!

Is this all for MW 1.35? If yes I could do a release.

**Comment by kghbln** [comment]
Thanks for the info. Will do after the merge. See https://github.com/SemanticMediaWiki/SemanticGlossary/pull/60#issuecomment-867414325
